### ISSUE TITLE
[mobile-Moto g84 G5] Incorrect Display of "un click" on the main page

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/androidAPP#4]
**ENVIRONMENT**: 
  - url: https://peviitor.ro
  - browser: Chrome
  - operating system: Android
  - telephone type: moto g84 G5

**STEPS TO REPRODUCE**: 
1. Open https://peviitor.ro
2. Check visually that "Locul de munca visat, la un click distanta" is displayed correctly.

**EXPECTED RESULTS**:
1. The text "Locul de munca visat, la un click distanta" is displayed correctly.

**ACTUAL RESULTS**:
1. "un click" from the text "Locul de munca visat, la un click distanta" is not displayed correctly. 

![image](https://github.com/user-attachments/assets/aed57037-1eb0-4587-8609-dbc764cf596a)

**Comment by lalalaurentiu** [comment]
Fixed please retest in version [1.3.3](https://expo.dev/artifacts/eas/86W92kQB1zouAru19i1XDG.apk)

**Comment by Lore78** [comment]
The bug was tested in version 1.3.3 and it is still persisting.
